services:
  - type: web
    name: hogar-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RAPIDAPI_KEY
        sync: false
      - key: RAPIDAPI_HOST
        value: idealista7.p.rapidapi.com
